apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-for-mongodb
spec:
  storageClassName: demo-fast-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: rocketchat-db
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    app: rocketchat
    tier: backend
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rocketchat-db
spec:
  serviceName: rocketchat-db
  replicas: 1
  selector:
    matchLabels:
      app: rocketchat
      tier: backend
  template:
    metadata:
      labels:
        app: rocketchat
        tier: backend
    spec: 
      containers:
      - name: mongodb
        image: mongo:4.0
        env:
        - name: MONGO_INITDB_DATABASE
          value: rocketchat
        command: 
        - "/bin/bash"
        - "-c"
        - mongod --smallfiles --replSet rs0 --bind_ip_all --noprealloc 
        ports:
          - containerPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-for-mongodb
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-rsinit
spec:
  template:
    spec:
      containers:
      - name:  mongo-rsinit
        image: mongo:4.0
        command: 
        - "/bin/bash"
        - "-c"
        - sleep 10 ;echo "rs.initiate()">init.js ; mongo --host rocketchat-db-0.rocketchat-db.demo-nativepod.svc.cluster.local:27017 init.js
      restartPolicy: Never
  backoffLimit: 6