apiVersion: v1
kind: Service
metadata:
  name: rocketchat-app
  labels:
    app: rocketchat
    tier: frontend
spec:
  type: LoadBalancer
  loadBalancerIP: 172.16.196.70
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: rocketchat
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketchat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketchat
      tier: frontend
  template:
    metadata:
      labels:
        app: rocketchat
        tier: frontend
    spec:
      containers:
      - name: rocketchat-app
        image: rocketchat/rocket.chat:latest
        env:
        - name: PORT
          value: "3000"
        - name: ROOT_URL
          value: "http://172.16.196.70"
        - name: MONGO_URL
          value: "mongodb://rocketchat-db-0.rocketchat-db.demo-nativepod.svc.cluster.local:27017/rocketchat"
        - name: MONGO_OPLOG_URL
          value: "mongodb://rocketchat-db-0.rocketchat-db.demo-nativepod.svc.cluster.local:27017/local"
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "1.5G"