apiVersion: v1
kind: Service
metadata:
  name: rocketchat-app
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 3000
    protocol: TCP
    nodePort: 31000
  selector:
    app: rocketchat
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketchat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketchat
      tier: frontend
  template:
    metadata:
      labels:
        app: rocketchat
        tier: frontend
    spec:
      containers:
      - name: rocketchat-app
        image: rocketchat/rocket.chat:latest
        env:
        - name: PORT
          value: "3000"
        - name: ROOT_URL
          value: "http://127.0.0.1:3000"
        - name: MONGO_URL
          value: "mongodb://rocketchat-db-0.rocketchat-db.default.svc.cluster.local:27017/rocketchat"
        - name: MONGO_OPLOG_URL
          value: "mongodb://rocketchat-db-0.rocketchat-db.default.svc.cluster.local:27017/local"
        ports:
        - containerPort: 3000